algoritmo "base e altura do retangulo"
// Função :
// Autor : erik marlon souza leite
// Data : 04/05/2020
// Seção de Declarações 
var
base,altura,area,perimetro:real

inicio
// Seção de Comandos 
escreval("digite a base e a altura do retangulo: ")
leia(base,altura)

area<-base*altura
perimetro<-base+base+altura+altura


escreval("a area e o perimetro do retangulo são:", area,perimetro)

fimalgoritmo
