algoritmo "preço de venda"
// Função :
// Autor : Erik Marlon Souza Leite
// Data : 04/05/2020
// Seção de Declarações 
var
nome:caractere
custo,preco,taxa:real

inicio
// Seção de Comandos
escreval("qual o nome do produto: ")
leia(nome)

escreval("qual o preço de custo do produto: ")
leia(custo)

taxa<-1.65
preco<-custo*taxa

escreval("então o preço de venda é:",preco)
 
fimalgoritmo
